server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ToDoListReactJava
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

app:
  client:
    url: http://localhost:5173

jwt:
  secret: ${JWT_SECRET}